### ISSUE TITLE
elm-make as Library

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-make#1]
It would be great if `elm-make` had a Haskell library interface. This would make it much easier to implement things on top of it, e.g., the `IO`/testing stuff.

All I really need is to be able to run the equivalent of `elm-make <File.elm> --output=<File2.js>` with a library function instead of relying on the user's PATH being correct.

**Comment by evancz** [comment]
I agree. I think we are gradually moving towards this. I think it'll happen independent of this issue, so I am going to close this.
