### ISSUE TITLE
Correct typo's in elm-make statement in terminal and get-started page

### ISSUE THREAD

**Issue by wintvelt** [elm-lang/elm-make#100]
The official [get started page](http://elm-lang.org/get-started#elm-make) says:

> elm make Main.elm --output=index.html

With command missing "-".

Small stuff, but threw me off as first time user (although loving elm so far!)

**Comment by evancz** [comment]
You can actually call things that way. `elm whatever` will translate into `elm-whatever` and call the right thing. We are considering getting rid of this behavior though!

**Comment by wintvelt** [comment]
Ok thanks for explaining!
