### ISSUE TITLE
Report warnings as errors

### ISSUE THREAD

**Issue by zgraggen** [elm-lang/elm-make#108]
It would be nice if there was a flag for elm-make to force warnings to fail the build. Warning often help to keep the code clean and maintainable. Since elm-make provides `--warn` I don't see a reason why there isn't a flag to fail the build for that.

Or maybe, if `--warn` is on just exit the build with an error code. Why else would you request warnings?

**Comment by ericbmerritt** [comment]
This would be something like warnings as errors, in various other compilers.

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-make/issues/98
