### ISSUE TITLE
Global Elm can't have to modules under the same namespace

### ISSUE THREAD

**Issue by bfad** [elm-lang/elm-make#109]
This code doesn't take into account the new module may be namespaced:

https://github.com/elm-lang/elm-make/blob/61a36ac09f88e80120b857bf9fa921d8c3d132ea/src/Pipeline/Generate.hs#L222-L229

This means if I have two modules such as `Users.List` and `Users.Show`, it will throw an error about there being two Elm modules named "Users" on the page.

**Comment by evancz** [comment]
Please provide an http://sscce.org/ and open a new issue explaining the problem through the concrete example.

**Comment by evancz** [comment]
I see what you are saying now by following the link, but I still think it'd be best to have an issue that says, running the following:

```bash
elm-make User/List.elm User/Show.elm
```

Results in the following error message at runtime:

```
...
```

With a title about "when compiling multiple Elm modules into one JS file, ..."

**Comment by bfad** [comment]
I'll open a properly formatted / detailed issue. Thanks for the pointers as I wasn't sure exactly what my build tool was doing to get this issue.

**Comment by bfad** [comment]
Doing some more investigating, and it turns out that elm-make is working just fine. My build tool was set to create separate output files for each main module and then concatenate them altogether. The upshot is that there were several copies of Elm and my other modules in my one file. I've fixed my build tool, and everything works great. Thanks again.

**Comment by evancz** [comment]
Awesome! Glad it's working, and thanks for the update! :)
