### ISSUE TITLE
repository field in elm-package.json only accepts github.com url

### ISSUE THREAD

**Issue by fernandocortez** [elm-lang/elm-make#110]
We have our own on premise enterprise GitHub where I work. I cannot compile with `elm-make` because the repository url is not `github.com` in the `elm-package.json`.

**Comment by evancz** [comment]
This is a known issue. Can you talk to folks on [the Elm slack](http://elmlang.herokuapp.com/) to see how people work around it for now? For example, just put stuff in there that isn't real. It's not perfect, but it'll work.

**Comment by fernandocortez** [comment]
ok thanks

**Comment by Mouvedia** [comment]
duplicate of #71
