### ISSUE TITLE
Elm-make reports "no store"

### ISSUE THREAD

**Issue by lijunle** [elm-lang/elm-make#112]
Hi, I am using Elm on Azure Web App. The deployment is failing.

I log onto the Web App console, install Elm from npm. `elm make` reports "no store" **without any more information**.

In `elm repl`, after I type one statement and press enter, it shows "elm-make: no store".

Run `elm package install -y` get the same error.

The issue is consistently repro. The commands are OK on my local Windows and OSX. Its Travis CI build is passing too.

I have no idea how this "no store" comes from. Could you please help?

**Comment by evancz** [comment]
I think it makes sense to ask about this on elm-discuss or the Elm slack channel.

It *may* be a bug with `elm-make` but it also may be some weird configuration stuff on Azure. Folks in the community can help you sort out which it is, and if it is a problems here, we can open an issue describing it in more detail.

**Comment by evancz** [comment]
Elm Slack: http://elmlang.herokuapp.com/
elm-discuss: https://groups.google.com/forum/?fromgroups#!forum/elm-discuss
community in general: http://elm-lang.org/community
