### ISSUE TITLE
The 2nd time you run elm-make on a file that has warnings, the warnings will not be returned anymore.. unless the module is named `Main`

### ISSUE THREAD

**Issue by halohalospecial** [elm-lang/elm-make#114]
Note: Using `elm-make 0.17.1` and `Ubuntu 16.04.1 LTS`.

Steps to reproduce:

1. Create a `Test.elm` file with the following contents:
 ```
 module Test exposing (..)
 x = 1
 ```

1. Run the following:
 `elm-make Test.elm --report=json --output=/dev/null --yes --warn`
 
 The output will be something like this:
 ```
 [{"tag":"missing type annotation","overview":"Top-level value `x` does not have a type annotation.","details":"I inferred the type annotation so you can copy it into your code:\n\nx : number","region":{"start":{"line":2,"column":1},"end":{"line":2,"column":2}},"type":"warning","file":"Test.elm"}]
 Successfully generated /dev/null
 ```

1. Run it again:
 `elm-make Test.elm --report=json --output=/dev/null --yes --warn`

 The output will just be:
 ` Successfully generated /dev/null`

1. Change the module name from `Test` to `Main`.

1. Run this:
 `elm-make Test.elm --report=json --output=/dev/null --yes --warn`

 The output will be the same as in Step 2.

1. Run it again:
  `elm-make Test.elm --report=json --output=/dev/null --yes --warn`

 The output will still be the same as in Step 2.

* Maybe the reason it's working if the module is named `Main` is because there's a special case for that.  See this comment: https://github.com/elm-lang/elm-make/blob/46ec85c0e8dc5f3427bde6e4f212b4f367ecbd07/src/Pipeline/Plan.hs#L44

**Comment by evancz** [comment]
Already reported in #27 and tracked in #98
