### ISSUE TITLE
Add `--color=always` flag for forcing color output

### ISSUE THREAD

**Issue by jamonholmgren** [elm-lang/elm-make#116]
Ref: https://github.com/madsflensted/elm-brunch/issues/28#issuecomment-247775995

Currently, `elm-make` will [suppress color coding](https://github.com/elm-lang/elm-make/blob/master/src/Report.hs#L35) if it thinks it's not operating in a TTY. Unfortunately, this means that launching `elm-make` from a build tool like `brunch` will result in non-color coded output.

According to @niklas, the common way to solve this is to allow a flag like `grep --color=always`. If we add this to `elm-make`, that would allow `elm-brunch` to use that flag and preserve color coding.

Thoughts?

**Comment by evancz** [comment]
Thanks for the issue! Tracking in https://github.com/elm-lang/elm-make/issues/123

**Comment by boxed** [comment]
Wish I could react to #123 ! Would be great to have this.
