### ISSUE TITLE
0.18 alpha: elm-make fails to generate correct JS when animation-frame is installed

### ISSUE THREAD

**Issue by eeue56** [elm-lang/elm-make#119]
The code: https://gist.github.com/eeue56/e2f9d66fb8ae6dbaec5bd1a976d4d4e6

elm-package.json

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/animation-frame": "1.0.1 <= v < 2.0.0",
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

Main.elm

```
import Html exposing (..)

main = text "hello"
```

# Problem

Run  `elm-make Main.elm` when animation-frame is in the package file.

## Expected output:

A HTML page with `hello` displayed.

## Actual output:

An error on line 1740 of the generated JS:`Uncaught TypeError: Cannot read property 'fromArray' of undefined`

# Possible solution

- Looks like `List` is not imported before `Cmd`
- This is somehow caused by including `animation-frame` in the package.
- The compiled code for Platform.Cmd turns `[]` into `_elm_lang$core$Native_List.fromArray([]));`. However, `_elm_lang$core$Native_List` has not been imported yet.
- Therefore it should be possible to fix it by importing `Native.List` or `List` in the first import in Cmd. Or, add `Native_List` to the import tree whereever list literal syntax is used.

**Comment by evancz** [comment]
I'm not sure if this is the ideal fix, but it works. It has some benefits:

  - The use of `fromArray([1,2,3])` came from someone saying that the JS output was not readable. Perhaps that concern has decreased since a few years ago. (In other words, there was no technical motivation for it being this way.)
  - It should be quicker in *theory* because there is nothing to inline. I tested this change with the perf comparison from recently, and it does pretty much the same, which is kind of odd.

**Comment by eeue56** [comment]
My only comment is that broken imports for Native seems to come up fairly often (in 0.17 there was the Json.Encode issue), so it might be worth investing some time into a js import system. This move seems fine for now though.

**Comment by nphollon** [comment]
Importing animation-frame still does not work. The error I am getting (for Noah's same sample program) is

`TypeError: _elm_lang$core$Native_Scheduler is undefined`

Should we re-open this issue, or should I create a new one?

**Comment by evancz** [comment]
New one with SSCCE would be best!
