### ISSUE TITLE
0.18 alpha: main with type `Html a` throws in debug mode

### ISSUE THREAD

**Issue by lukewestby** [elm-lang/elm-make#120]
SSCCE:

**Main.elm**
```elm
module Main exposing (main)

import Html

main =
    Html.text "hello"
```

**build.sh**
```
elm-make ./Main.elm --debug
```

Result:
![screen shot 2016-10-13 at 10 00 47 am](https://cloud.githubusercontent.com/assets/1508245/19354347/f9b6a80c-912b-11e6-8f5d-f97b959b2abd.png)

**Comment by evancz** [comment]
I made a partial fix, but the rest needs a change in the compiler. I think it makes sense to make the decision about `main` and then do this fix at the same time, so it can all be out in the next batch of binaries. Don't let me forget!

**Comment by lukewestby** [comment]
Sounds good! I'll check in on elm-dev when you release the next binaries

**Comment by evancz** [comment]
Okay, got a similar report from https://github.com/elm-lang/elm-reactor/issues/209 and made the fix. Thanks again for the report!
