### ISSUE TITLE
[alpha] Runtime exception with --debug when Json.Encode.null in init

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/elm-make#122]
Using Ubuntu 16.04, and 0.18 alpha.

The code below (initialising with `null`) fails to start and causes an exception, while using the commented out section (with `string`) works fine.

```
module Test exposing (main)

import Html exposing (..)
import Json.Encode as E exposing (Value)

-- MODEL

type alias Model =
    { gmap : Value
    }

init : (Model, Cmd Msg)
init =
    ( Model E.null, Cmd.none )
    -- ( Model (E.string "Dummy text"), Cmd.none )

-- UPDATE
type Msg
    = North

update : Msg -> Model -> (Model, Cmd Msg)
update message model =
    model ! []
-- VIEW

view : Model -> Html Msg
view model =
    text "hello world"

main =
  Html.program
    { init = init
    , update = update
    , view = view
    , subscriptions = always Sub.none
    }
```

[If the fix is **not** to test for null values, then note that in my code that originally ran into this bug, just fixing the init value to use `Encode.string "dummy string"` was not enough, as I got another null value being passed to init (which I have not tracked down yet) - see https://github.com/simonh1000/elm-google-maps-2]

**Comment by evancz** [comment]
Thanks for the report, should be fixed if you get rid of `elm-stuff/` and rebuild!
