### ISSUE TITLE
Memory leak when using List.sortBy

### ISSUE THREAD

**Issue by butchcom** [elm-lang/elm-make#124]
I had the following code in a module:
```elm
f a =
    { a | b = List.sortBy a.b }

c = List.map f xs
```
When I ran `elm make`, the 'module process bar' stopped after a while and the my machines memory was filled up to the point where the os just froze.

I know that the usage of `List.sortBy` is wrong, but I don't think that it should lead to a total halt of the system. There may be some memory leak in `elm make`.

**Comment by evancz** [comment]
For me, this fails immediately with:

![screen shot 2016-12-21 at 11 43 37 pm](https://cloud.githubusercontent.com/assets/1658058/21416300/5af50924-c7d7-11e6-8021-15986bb8f680.png)

I suspect your http://sscce.org/ is missing some information. If you can get a piece of code that exactly replicates the problem you saw, please open it on https://github.com/elm-lang/elm-compiler/issues
