### ISSUE TITLE
Using ports without importing Json causes a build failure

### ISSUE THREAD

**Issue by eeue56** [elm-lang/elm-make#127]
# Problem

- Make a minimal program as shown [here](https://gist.github.com/shamansir/c2f857a4f65e521b320a6a62dd7189f5)
- Do not import anything that uses Json
- Use a port
- The decoders used by ports will not be found

# Solution

- Import Json anywhere in the tree
- So then it could be fixed by adding a json import in `Basics.elm` without being too problematic

**Comment by shamansir** [comment]
IMO it's better to auto-include `Json.Decode` only when incoming ports are used (or there's `programWithFlags`), decoding JSON is not required in every case. i.e. outgoing ports are not failing with this configuration (`port trigger : Bool -> Cmd msg`).

**Comment by pauldijou** [comment]
I didn't see this issue at first, but I wanted to highlight that you have the exact same problem when using flags inside your program for the same reasons (using `Json.Decode` but not imported). More infos here: https://github.com/elm-lang/elm-make/issues/134

**Comment by evancz** [comment]
The upcoming code crawls dependencies from `main` so these should get included. At the very least, the mechanism works different now, so we should test with 0.19 and get it fixed before it goes out.

**Comment by dkokic** [comment]
Is this project still being maintained? ;-)
