### ISSUE TITLE
Could not find uneeded type constructor error while checking types.

### ISSUE THREAD

**Issue by kasbah** [elm-lang/elm-make#13]
With [the current head of my project](https://github.com/kasbah/mooltipass.hid-app/tree/7538052aeca55e05db27dbc921f5d03febdfe05a) (and using latest elm-make from git) I get this error when compiling for the second time: 
```
Error in src/background/Main.elm:

Could not find type constructor 'GuiState.Action' while checking types.

make: *** [build/background/elm-background.js] Error 1
```
`GuiState.Action` is not a constructor that is needed for this compilation step. It is part of a previous compilation step (the application is separated into gui and background). You should be able to reproduce with these steps:

```
git clone git@github.com:kasbah/mooltipass.hid-app
cd mooltipass.hid-app
git checkout 7538052
make
touch src/background/Main.elm
make
```

**Comment by kasbah** [comment]
So I am now working around this issue by [renaming the module `ChromeMessage` in the background to `ChromeBgMessage`](https://github.com/kasbah/mooltipass.hid-app/commit/b11f6dad22bdcf2ba6eb18fd769e7ce1bf177236). There is another, different `ChromeMessage` in the GUI which is part of a separate compilation step.  My guess would be that elm-make is caching too aggressively and not separating the two compilations properly.

**Comment by evancz** [comment]
I see how this causes unexpected behavior, but I'm not sure how to do things such that "the right thing" happens. If the modules have exactly the same name, and are being compiled within the same project, it seems like that is just a problem.

Is there precedent in other languages for allowing this case and some how disambiguating based on file path?

**Comment by evancz** [comment]
This may be related to https://github.com/elm-lang/elm-compiler/issues/826 which is fixed in the latest version of elm-compiler. Module names cannot clash between packages anymore.

I'm not sure how to address this issue better as is, so I am going to close this. If there is still something wrong, please open an issue with a [SSCCE](http://sscce.org/).
