### ISSUE TITLE
Debug flag causes uncaught type error

### ISSUE THREAD

**Issue by igotlegs** [elm-lang/elm-make#136]
When using Elm 0.18 with debug flag my code crashes at runtime with `Uncaught TypeError: Cannot read property 'nativeBinding' of undefined`

I stripped down my code to barebones in order to reproduce this bug: https://github.com/igotlegs/elm-debug-bug

Using OSX El Capitan 10.11.5 with Chrome 54.0.2840.98 (64-bit)

**Comment by evancz** [comment]
I need you to get the example down smaller. It is really hard to know if this is definitely caused by Elm with all the other code in there.

**Comment by evancz** [comment]
Not sure what is going on and cannot debug based on whole repos.

Maybe it is something here? https://github.com/elm-lang/virtual-dom/issues/98

If not, please open an issue on that repo with a single Elm file that can reproduce the error.
