### ISSUE TITLE
No "unused function" warnings

### ISSUE THREAD

**Issue by zaboco** [elm-lang/elm-make#137]
Given I have a file which has a function that is not (1) exposed or (2) used internally, I would expect that `elm-make --warn` prints some warnings about that. Instead, it just compiles as normally.

```elm
module Main exposing (main)

import Html exposing (Html, text)


main : Html msg
main =
    text "Hello World!"


unused : ()
unused =
    ()
```

Using `elm-make 0.18`

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-make/issues/98, thanks for the suggestion!
