### ISSUE TITLE
Send Msgs from debugger (feature request)

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/elm-make#138]
Rather than the debugger just showing the Msgs that _have_ been sent, it'd be cool if it could also show the Msgs that _could_ be sent, and you could send them by clicking on them. The debugger already shows the model after each Msg, so you could play with your program without having to code the UI.

**Comment by evancz** [comment]
I'll share this idea with folks who are working on elm-reactor and the debugger.

One issue is that UI messages do not account for all possible messages, so I'm not certain how possible this is in general. Anyway, does not make sense to track on the elm-make repo, but thanks for the suggestion!

**Comment by willnwhite** [comment]
Cool, thanks Evan. I wasn't sure where to put this, just knew that `--debug` was an elm-make option. Guess I should keep an eye on elm-dev to follow the discussion?

**Comment by willnwhite** [comment]
This could be used to automatically write tests for you. 

Clicking on a Msg would transform the current model into the new model. If the new model is as expected, you could click to say that it is, and that could be used to write a test. To use Counter as an example:

```
model = 0

update msg model =
  case msg of 
    Up ->
      model + 1
    Down ->
      model - 1
```
My model starts as `0`. I click `Up`, I get `1`. This is as expected so I accept. `update Up 0 == 1` is now a test that the code has to pass.

**Comment by willnwhite** [comment]
I've just realised that this feature is independent of being able to click on Msgs, i.e. it could work with the debugger as it is now. But I don't know where to raise this feature request. Is there a repo I'm missing for the debugger?

**Comment by willnwhite** [comment]
Found it: https://github.com/elm-lang/virtual-dom/blob/master/src/VirtualDom/Debug.elm

**Comment by willnwhite** [comment]
Sending messages from the debugger would also be good when you can't use your UI to test your program because incoming ports are responsible for getting the UI into a state where it can be used.
