### ISSUE TITLE
Turn on '--warn' flag as a default.

### ISSUE THREAD

**Issue by simnalamburt** [elm-lang/elm-make#141]
> Don't save code quality for later! ― by [`elm-make`]

I really love this sentence!

The warning of [`elm-make`] is very friendly and extremely effective in improving code quality. It is very sad that this option is not turned on by default. If this option is turned on by default, it will greatly enhance the overall code quality of the Elm ecosystem.

How do you think about by removing the `--warn` option to always have warning turned on, and instead adding an option like` --nowarn` to turn off the warning only if the programmer wants to?

[`elm-make`]: https://github.com/elm-lang/elm-make

**Comment by heejongahn** [comment]
I also agree with @simnalamburt.

**Comment by evancz** [comment]
Added to #98
