### ISSUE TITLE
Feature: Optimize the build output

### ISSUE THREAD

**Issue by maraisr** [elm-lang/elm-make#142]
First off - love the language! Absolutely brilliant, just a tad concerned about the output size.

With reference to line [386](https://github.com/elm-lang/elm-make/blob/master/src/Pipeline/Generate.hs#L386) onwards, can we do something like:

```js
let alpha = 'abcdefghijklmnopqrstuvwxyz';

function createFunction() {
    return new Function(...arguments, `return ${arguments[0]}.arity === ${arguments.length - 1} ? ${arguments[0]}.func(${[...arguments].slice(1).join(', ')}) : ${arguments[0]}${[...arguments].slice(1).map(v => `(${v})`).join('')};`);
}

new Array(8).fill(null).forEach((val, key) => {
    window[`A${key+2}`] = createFunction.apply(this, ['fun'].concat(new Array(key+2).fill(null).map((v, k) => alpha[k])))
});
```

or es5:

```js
var alpha = 'abcdefghijklmnopqrstuvwxyz';

function createFunction() {
    return new (Function.prototype.bind.apply(Function, [null].concat(Array.prototype.slice.call(arguments), ['return ' + arguments[0] + '.arity === ' + (arguments.length - 1) + ' ? ' + arguments[0] + '.func(' + [].concat(Array.prototype.slice.call(arguments)).slice(1).join(', ') + ') : ' + arguments[0] + [].concat(Array.prototype.slice.call(arguments)).slice(1).map(function (v) {
        return '(' + v + ')';
    }).join('') + ';'])))();
}

new Array(8).fill(null).forEach(function (val, key) {
    window['A' + (key + 2)] = createFunction.apply(undefined, ['fun'].concat(new Array(key + 2).fill(null).map(function (v, k) {
        return alpha[k];
    })));
});
```

to like dynamically create these functions? That way in the future we can analyse the app, work out what the max arity is going to be an adjust that array.

You could do something similar with the F* functions.

Just a thought...

Would like to spark the conversion (if not already sparked), to output some sort of ES6 output, so that we can have the goodness of tree shaking or something.

**Comment by evancz** [comment]
Optimizing output is in the plans already, and I don't want to track it here.

In the meantime, use a JS minifier like Closure Compiler or UglifyJS. Output that starts as 300kb will go down to ~50kb with minification, and then down to ~30kb after gzip. So the output is not actually very big as is.

There are many ways to do better than this though, and that's quite high on my priority list.

**Comment by screendriver** [comment]
Any news on that @evancz ? Are there any plans to integrate a minifier / uglyfier into `elm-make`?
