### ISSUE TITLE
Debugger hides important information

### ISSUE THREAD

**Issue by sporto** [elm-lang/elm-make#143]
The debugger is very useful, but I still find myself using `Debug.log` a lot because I cannot see all the information I need in the debugger.

![image](https://cloud.githubusercontent.com/assets/1005498/21296755/edd2f084-c5c6-11e6-8309-9a4421f4bd3d.png)

Specifically, the information about the messages received on the left is just a partial. It would be create if the right pane would show this information entirely.

**Comment by evancz** [comment]
Duplicate of https://github.com/elm-lang/virtual-dom/issues/49.

We're thinking about UI for something like this!
