### ISSUE TITLE
elm-make: type applications should start with a type atom

### ISSUE THREAD

**Issue by Zimmi48** [elm-lang/elm-make#144]
It seems that this error was reported before but not for 0.18.
I did not try to minimize the faulty code (no time for that). I hope the error report is useful nonetheless.
The code [here](https://github.com/Zimmi48/Test-Pedago/blob/c8a7bf097ae01ca2286a0eed4cf29382207970ea/src/Game.elm) makes `elm-make` crash with the following error message:

```
-- TYPE MISMATCH -------------------------------------------------- src/Game.elm

The right side of (|>) is causing a type mismatch.

200|                             { answer = questionState.answer |> removeFromAnswer }
201|>                                |> Active

(|>) is expecting the right side to be a:

    { ... } -> a

But the right side is:

    elm-make: type applications should start with a type atom
CallStack (from HasCallStack):
  error, called at src/Reporting/Render/Type.hs:411:9 in elm-compiler-0.18-8FVx3ZbYiisIpZXxx99S4A:Reporting.Render.Type
```

EDIT: for the record I'm using Linux (NixOS) but I hope the error is not specific to this OS.

**Comment by Zimmi48** [comment]
I've minimized the example to this:
```
type X a = X Int

v = if True then X 0 else { x = 0 }

f : X -> ()
f { x } = ()
```
The error report is the following:
```
-- TYPE MISMATCH ------------------------------------------------------- Bug.elm

The branches of this `if` produce different types of values.

3| v = if True then X 0 else { x = 0 }
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The `then` branch has type:

    elm-make: type applications should start with a type atom
CallStack (from HasCallStack):
  error, called at src/Reporting/Render/Type.hs:411:9 in elm-compiler-0.18-8FVx3ZbYiisIpZXxx99S4A:Reporting.Render.Type
```
One can reproduce this on elm-lang.org/try but the error message is cut.

**Comment by Seurimas** [comment]
This is likely issue #1373.

Additional note to googlers: I ran into this same root issue because I was not specifying a complete type (e.g. "f : X -> ()" is incorrect above, as it should be "f : X a -> ()")

**Comment by Zimmi48** [comment]
You mean elm-lang/elm-compiler#1373.
