### ISSUE TITLE
Maximum call stack size exceeded error with '--debugger'

### ISSUE THREAD

**Issue by Chadtech** [elm-lang/elm-make#145]
Working on a project, I encountered a call stack error. I boiled my code down into the simple code snippet linked to below and experimented a bit with it. I get a 'maximum call stack size exceeded' error when running the snippet in elm-reactor and with 'elm-make --debug', but not with 'elm-make' and elm-lang.org/try. Another fellow in the Elm slack channel said he wasnt getting the error in 0.17.1.

Heres the code snippet Im referring to: https://gist.github.com/Chadtech/f2f5f1d714eea51a8a0b687b93110b15

EDIT: Im running all my code in Chrome, on my mac running Sierra 10.12.1

**Comment by evancz** [comment]
I think this is covered by https://github.com/elm-lang/virtual-dom/issues/98

Thanks for the report!
