### ISSUE TITLE
Hard to generate easy-to-browse documentation for product-y projects

### ISSUE THREAD

**Issue by ento** [elm-lang/elm-make#146]
It'd be useful to be able to have a searchable documentation for projects that are not intended to be published, i.e. projects for apps/products. However, currently (Elm 0.18) there's no official way to do so. Because..

1. Hard to generate `documentation.json` for product-y projects
   - `elm-make`'s `--doc` option only generates documentation for modules that are exposed, but it's unrealistic to maintain the list by hand.
      - We currently have 300 Elm modules in our codebase: we'd rather not add those to exposed-modules manually ..which might not be that bad if we actually tried

2. No easy way to make a viewer for `documentation.json` that can be privately hosted
   - Hosting your own package.elm-lang.org is not really streamlined/documented: https://github.com/elm-lang/package.elm-lang.org/issues/110
   -  There's an attempt at a local viewer, but hasn't been updated for two years: https://github.com/jcollard/elm-doc-viewer

Other nice-to-haves:

- Our current internal guideline is to document modules that are reusable across different pages: for non-reusable modules, we want to relax the enforcement to have doc comments for every exposed thing

Current workaround:

- [elm-doc](https://github.com/ento/elm-doc) generates `documentation.json` by exposing modules temporarily, and then generates all necessary files to make a static clone of package.elm-lang.org.

**Comment by evancz** [comment]
The long term idea is to have `elm reactor` give you a bunch of viewing options. See the code, see the docs, see it in REPL, see it in debug mode, etc. So that is where this will go eventually. I do not think keeping this issue open will impact time-to-completion, so I will close.
