### ISSUE TITLE
`Success! Compiled 0 modules.` is confusing

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/elm-make#148]
From Slack:

> A: I'm trying to run elm-make on a file but I get: `Success! Compiled 0 modules. `. The same file works with `elm-reactor` so I'm not sure what I'm doing wrong :confused:
> B: You can't run the compiled file, right?
> B: I see `Success! Compiled 0 modules.` a lot but I'm sure I can still run the compiled file.
> A: hmmm. yeah sorry, it works

I think `Success! Compiled 0 modules.` is confusing when there's also `Success! Compiled 1 module.`.

**Comment by willnwhite** [comment]
Is the message `Compiled x modules.` necessary? What about just `Success!`?

**Comment by evancz** [comment]
Made it so the message is `Success!` when there is nothing to compile.

**Comment by dustinfarris** [comment]
actually the "0 modules" message was beneficial to me when I was troubleshooting why elm-make wasn't working

**Comment by willnwhite** [comment]
How do you mean?
