### ISSUE TITLE
Add author, name and version to documentation.json

### ISSUE THREAD

**Issue by Positive07** [elm-lang/elm-make#149]
Well the issue may explains itself, first I wanna say that when I talk about `documentation.json` I mean the files located at [packages.elm-lang.org/packages/elm-lang/core/5.0.0/documentation.json](packages.elm-lang.org/packages/elm-lang/core/5.0.0/documentation.json).

Basically right now there is no way to tell which version of the module the `documentation.json` is for. So if the package is updated, or the `documentation.json` file is moved to other folder, the context is lost and we can't tell which module and version the `documentation.json` is for. It would be better if this three fields would be added to the `documentation.json` file at compile time.

Issue #28 would benefit from this. Also the offline documentation project at [elm-lang/projects](https://github.com/elm-lang/projects)

I understand that not all this information may be available for projects (not packages) so we should carefully approach this.

**Comment by Positive07** [comment]
Other thing that could be added to that file, is the readme which is commonly the first page of [packages.elm-lang.org](packages.elm-lang.org) documentations.

**Comment by evancz** [comment]
Tracking in #98. I suspect we will do a big batch on editor plugin support to cover stuff like this. Anyway, thank you for the suggestion!
