### ISSUE TITLE
Make "Success!" green

### ISSUE THREAD

**Issue by dustinfarris** [elm-lang/elm-make#151]
When using with elm-live, hard to tell when I've finally resolved all compiler errors.

![screenshot 2017-02-14 18 42 00](https://cloud.githubusercontent.com/assets/1087165/22925956/98b6c82c-f2e5-11e6-8a5c-2bf96b5e8b6c.png)

A brighter visual cue would be nice.

**Comment by evancz** [comment]
Perhaps `elm-live` can do a bright color to mark when it is rebuilding. I think putting the `You've changed .... Rebuilding!` in purple would have the same effect that you are looking for.
