### ISSUE TITLE
Mandatory requirement for link to github .git repo is unusual

### ISSUE THREAD

**Issue by chatterbeak** [elm-lang/elm-make#155]
Just a little nit:

Is it really necessary to "force" a github .git repository for those using elm-make?

`Error in $: Missing field "repository" which should hold a link to the project's GitHub repo.`

It would be nice if this field were optional. Or at least make this just a warning.

It also requires it ends in .git. My repo doesn't

` https://git-codecommit.us-east-1.amazonaws.com/v1/repos/chatterbeak.dashboard`

So I get:

```
D:\repos\chatterbeak.dashboard\elm [develop ↑ +0 ~1 -0 !]> elm-make
Error in $: Problem with the "repository" field.

The given URI does not end with .git
D:\repos\chatterbeak.dashboard\elm [develop ↑ +0 ~1 -0 !]> elm-make
Error in $: Problem with the "repository" field.

The given domain does not start with <https://github.com/>
D:\repos\chatterbeak.dashboard\elm [develop ↑ +0 ~1 -0 !]>
```

To reproduce: 

- Make an elm-package.json that's missing the repository field
- Make an elm-package.json where the repository url doesn't end in .git
- Make an elm-package.json where the repository isn't on "github"

**Comment by evancz** [comment]
This has been reported elsewhere and will be nicer in future versions. I'd prefer to track it a different way, so I'm closing this one.

**Comment by chatterbeak** [comment]
I got bit by a related problem that I found in another issue--my repo names have multiple dots in it, which simply crashed the runtime! Thanks for taking care of this.
