### ISSUE TITLE
elm-make reports unhelpful internal error

### ISSUE THREAD

**Issue by jDomantas** [elm-lang/elm-make#157]
I tried to run this program in http://elm-lang.org/try:

```elm
import Html

main = Html.text "test"

type Foo = Foo

foo : Foo -> Foo
foo Foo = Debug.crash "not implemented"
```

And I got this error:

```
elm-make: the annotation added in 'depattern' should not be observed!
elm-make: thread blocked indefinitely in an MVar operation
```

Trying to compile the same program locally also fails with same error. Elm make version: `elm-make 0.18 (Elm Platform 0.18.0)`.

**Comment by jDomantas** [comment]
Example could be minimized even further, you can get that error on http://elm-lang.org/try with as much as

```elm
foo : () -> ()
foo () = Debug.crash "not implemented"
```

**Comment by brianhempel** [comment]
Appears to be the same issue as https://github.com/elm-lang/elm-compiler/issues/1278

**Comment by brianhempel** [comment]
Workaround: If you just need a thunk to crash, change `()` to `_` in the definition.

```elm
foo : () -> ()
foo _ = Debug.crash "not implemented"
```

**Comment by evancz** [comment]
Thanks for linking to the other version of this @brianhempel!

It seems to be fixed in my development build, and a temporary fix has been found until that is released.
