### ISSUE TITLE
--warn should warn about unused functions exposed from import

### ISSUE THREAD

**Issue by ahstro** [elm-lang/elm-make#158]
Here, `div` is exposed from `Html` but never used. `--warn` should complain, similarly as it would if importing an unused module.

```elm
module Main exposing (..)

import Html exposing (div, text)


main : Html.Html msg
main =
    text "foobar"
```

Similar to #137 

Edit: This regards version 0.18.0 of elm-make

**Comment by evancz** [comment]
Tracking in #98. Thank you for the suggestion!
