### ISSUE TITLE
ΓùÅ Text Displayed When Using Cmder

### ISSUE THREAD

**Issue by theGeekPirate** [elm-lang/elm-make#167]
OS: Windows 10
Version: 0.18 (Elm Platform 0.18.0)
Terminal: [Cmder](http://cmder.net/)

You can see the issue below:
![cmder_defect](https://user-images.githubusercontent.com/1026070/27258197-2e3a9ba2-53a9-11e7-9fb9-b054b13862a9.png)

```
λ elm-make Main.elm --output=main.html
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 5.1.1
    elm-lang/html 2.0.0
    elm-lang/virtual-dom 2.0.4

Do you approve of this plan? [Y/n] Y
Starting downloads...

  ΓùÅ elm-lang/virtual-dom 2.0.4
  ΓùÅ elm-lang/html 2.0.0

ΓùÅ elm-lang/core 5.1.1
Packages configured successfully!
Success! Compiled 38 modules.
Successfully generated main.html
```

**Comment by evancz** [comment]
This should be fixed in 0.19 because it checks for Windows and shows uglier characters from ASCII
