### ISSUE TITLE
Debugger controls can get covered by application elements

### ISSUE THREAD

**Issue by lzrski** [elm-lang/elm-make#168]
I am very much unsure if this repo is correct to file this issue, but let me try.

In the browser the Elm Debugger controls (introduced in 0.18 with `elm-make --debug` flag) can easily be covered by the application elements, e.g. if they have position `absolute`. A case of that bug is discussed in https://github.com/debois/elm-mdl/issues/270.

I believe this should be solved by changing the setup of Elm debugger instead of  each particular library / application.

**Comment by avh4** [comment]
Hello!  the correct repo for this issue would be https://github.com/elm-lang/virtual-dom  as the implementation and appearance of the debugger is defined there.

**Comment by lzrski** [comment]
Thank you. Migrated.
