### ISSUE TITLE
Feature request: --warn-ignore flag for ignoring certain files when using --warn

### ISSUE THREAD

**Issue by HariGyogu** [elm-lang/elm-make#173]
I would find this very useful, as my project has quite a few haskell-generated .elm files, and I would like to ignore warnings coming from them.

Usage could be for example

```
elm-make --warn --warn_ignore [src/ignoreme.elm, src/ignoreme2.elm] src/Main.elm
```

**Comment by evancz** [comment]
Tracking in #98. Thanks for the suggestion!
