### ISSUE TITLE
[feature suggestion] elm-make auto insert type annotation

### ISSUE THREAD

**Issue by beenotung** [elm-lang/elm-make#184]
When using elm-make --warn, it warn and provide a guess of the function annotation.
It will be great if the tool can auto insert the type annotation if it can be surely guessed.

I am working it on, will make a pull request soon.
If there is an existing tool doing that, please kindly point me to that. Thank you.

**Comment by beenotung** [comment]
I'm using this simple external tool for now:
`build` and `tools/insert-type.js` in https://github.com/beenotung/five-element/commit/451bb559327df4304ed00aadda99deebc42fb5b3

Will invest on the compiler source code later on.

**Comment by beenotung** [comment]
i wonder if there is typescript definition for the output json

**Comment by evancz** [comment]
I think this should live in developer tooling. It makes sense for the compiler to provide the infrastructure to figure things out, but not to actually change the code. I think it is important to separate these concerns clearly.

**Comment by beenotung** [comment]
maybe can be a package of the elm-x family?
Like golang do for `go fix`
