### ISSUE TITLE
Recursive anonymous functions in List fold consume all CPU

### ISSUE THREAD

**Issue by jwbrew** [elm-lang/elm-make#188]
`List.foldl (\a b -> b a) () []` does not generate a compiler error and instead spawns multiple processes and consumes all the CPU. 

I assume It has something to do with the fact that the type definition for the anonymous function is recursive, `a -> b -> (a -> (a -> (a -> ...`.

**Comment by zwilias** [comment]
Thanks for the report, @jwbrew. Looks like this will be [fixed](https://github.com/elm-lang/elm-compiler/issues/1602) when 0.19 is released :)
