### ISSUE TITLE
Ask Before Creating an elm-package.json file

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-make#2]
The current behavior is bad because it doesn't tell the user it's going to create a file and the user may have input the command in error.

The interaction should be
```
1. Inform the user they don't have an elm-package.json and they need one to use elm-make
2. Ask if they want to make one
3. If yes, either interactively build one or tell them you put a default one in
4. Exit the program
```
the user can then fill it in and then install things the second time.

**Comment by joeandaverde** [comment]
+1 I'm tired of mistakenly creating `elm-stuff` and `elm-package.json`

**Comment by evancz** [comment]
Tracked in #98
