### ISSUE TITLE
JSON reporting loop does not take the 'warn' argument into account.

### ISSUE THREAD

**Issue by ajhager** [elm-lang/elm-make#24]
Warnings should be opt-in like for normal reporting. 

edit:  This issue is that I am getting back warnings in the json reporter whether I asked for them or not. I will talk more about json reporting in issue #25, but it just seemed counter intuitive that changing the report format would change the behavior. I just thought it had been overlooked.

**Comment by evancz** [comment]
Can you edit the description of this issue to summarize the current behavior? What is getting output? Knowing that the JSON output was meant for machine consumption, my intent was to label things as error and warning and let the user filter things out however they wanted. In that world, it seems weird to opt-in to warnings.

**Comment by ajhager** [comment]
I think this issue can be closed. I have added support in elm-vim to filter out warnings if needed, and I do not feel strongly either way if the --warn flag is used with json output.
