### ISSUE TITLE
Possible to generate warning and error reports at the same time (Problem for json)

### ISSUE THREAD

**Issue by ajhager** [elm-lang/elm-make#25]
Below is a reproducible program that generates a warning about Window being unused, and then error messages. With normal reporting it does not matter, but with json this produces the text for two different arrays of objects (one for warnings and another for errors.) This makes it sloppier in an IDE plugin to parse the report correctly.

It would be nice if all errors and warnings were in one single json array in the report.

```elm
module Main where

import Html exposing (..)
import Window

main = text + "Test"
```

**Comment by evancz** [comment]
Makes sense and seems pretty easy to do.

On this note, do you have any other concerns about the current setup? Like, do you want entries for modules that succeed? I was thinking that'd be useful for [this feature](https://github.com/elm-lang/projects#visualize-compilation), and I'm curious how it'd impact you.

One question I don't know how to answer is "What is the ideal JSON output for --report=json?" so if you have other thoughts on this please share them!

**Comment by evancz** [comment]
Let me put it another way. In your ideal world, what would the output of `--report=json` give you exactly?

**Comment by ajhager** [comment]
First, it would be great if json reporting gave back a single array with any information. Right now I am having to check if there is: 

one line of plaintext,
```json
Successfully generated elm.js
```

one line of json and one of plaintext,
```json
[{"tag":"unused import","overview":"Module `ElmTest.Run` is unused.","details":"","region":{"start":{"line":7,"column":1},"end":{"line":7,"column":24}},"type":"warning","file":"TestMain.elm"}]
Successfully generated elm.js
```

or two lines of json.
```json
[{"tag":"unused import","overview":"Module `Window` is unused.","details":"","region":{"start":{"line":26,"column":1},"end":{"line":26,"column":14}},"type":"warning","file":"Todo.elm"}]
[{"tag":"TYPE MISMATCH","overview":"The type annotation for `main` does not match its definition.","subregion":null,"details":"As I infer the type of values flowing through your program, I see a conflict\nbetween these two types:\n\n    Signal Html\n\n    number","region":{"start":{"line":307,"column":8},"end":{"line":307,"column":19}},"type":"error","file":"Todo.elm"},{"tag":"TYPE MISMATCH","overview":"The right argument of (+) is causing a type mismatch.","subregion":{"start":{"line":309,"column":17},"end":{"line":309,"column":44}},"details":"As I infer the type of values flowing through your program, I see a conflict\nbetween these two types:\n\n    number\n\n    Html","region":{"start":{"line":309,"column":3},"end":{"line":309,"column":44}},"type":"error","file":"Todo.elm"},{"tag":"TYPE MISMATCH","overview":"The left argument of (+) is causing a type mismatch.","subregion":{"start":{"line":309,"column":3},"end":{"line":309,"column":13}},"details":"As I infer the type of values flowing through your program, I see a conflict\nbetween these two types:\n\n    number\n\n    (a -> b) -> Signal a -> Signal b","region":{"start":{"line":309,"column":3},"end":{"line":309,"column":44}},"type":"error","file":"Todo.elm"},{"tag":"TYPE MISMATCH","overview":"This argument is causing a type mismatch.","subregion":{"start":{"line":309,"column":39},"end":{"line":309,"column":44}},"details":"As I infer the type of values flowing through your program, I see a conflict\nbetween these two types:\n\n    Model\n\n    Signal Model","region":{"start":{"line":309,"column":17},"end":{"line":309,"column":44}},"type":"error","file":"Todo.elm"}]
```

I would be happy with getting the warnings, errors, and successes (and any other information) in one big array that I can just filter by tag.

Returning an object of arrays indexed by the type might also make sense so that the user doesn't have to go through and do the filtering each time:

```json
{
    "warning": [{...}, {...}],
    "error": [{...}, {...}],
    "success": [{...}, {...}],
}
```

Either way, the json output makes my job so much easier!

**Comment by evancz** [comment]
Closing in favor of #47 which will address this and others
