### ISSUE TITLE
Generate docs for subpackages

### ISSUE THREAD

**Issue by ajhager** [elm-lang/elm-make#28]
So that tools can use the docs for dependency packages without need to run `elm-make --docs` under each one.

**Comment by evancz** [comment]
Can't we just distribute the docs somehow? Seems easier / less error prone than trying to reproduce them every time. Does that seem reasonable?

**Comment by evancz** [comment]
Like, as it is, you can always get the full docs file from the package website. Does it need to be fancier than that?

**Comment by evancz** [comment]
http://package.elm-lang.org/packages/elm-lang/core/2.1.0/documentation.json

**Comment by dnalot** [comment]
Will that ever get too big? @deadfoxygrandpa was looking into the same thing. Maybe there's a longer term solution that would give us types within expressions too.

**Comment by ajhager** [comment]
In elm-oracle, I do indeed already pull the documentation.json file from the package site. I am happy with continuing to use that, but distributing the file with the package would be great. The idea behind this Issue is so that elm-oracle doesn't need to do an http get for each dep the first time.

In summary, I don't care if it is generated automatically when the dependencies are installed or just bundled with the package.

**Comment by evancz** [comment]
Tracked in #98
