### ISSUE TITLE
UX of "Error reading build artifact"

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-make#30]
After upgrading to Elm 0.15.1, I get this:

```
Error reading build artifact elm-stuff/build-artifacts/elm-lang/core/2.1.0/Array.elmi
    The file was generated by a previous build and may be outdated or corrupt.
    Please remove the file and try again.
```

Is there any reason not to structure `elm-stuff` like this?

```
elm-stuff/
  build-artifacts/
    0.15.0/
      NoRedInk/
      elm-lang/
      evancz/
    0.15.1/
      NoRedInk/
      elm-lang/
      evancz/
```

This seems like it would make it so I never had to see this error again. :smile:

**Comment by rtfeldman** [comment]
Re: https://github.com/elm-lang/elm-compiler/issues/976#issuecomment-117375008

Either option would be preferable to the status quo. This suggestion was my first thought, but I actually have a use case for keeping both versions around.

I haven't upgraded our Rails integrations to use Elm 0.15.1 yet (blocked on https://github.com/kevva/elm-bin/issues/23), but I still wanted the improved error messages, so I ran the OS X installer in order to at least get them in `elm-repl`. However, since my project only gets one `elm-stuff` directory, I have to manually blow it away each time I switch from `elm-repl` to testing out the results in the browser.

It would be nice if the tool blew away the directory for me, but it would be nicer still if my `elm-repl 0.15.1` and my build tools' `elm-make 0.15.0` could coexist peacefully. :smiley:

**Comment by Apanatshka** [comment]
That sounds like a good arguments for the versioned build-artifact directories.

**Comment by rtfeldman** [comment]
Another motivating use case for changing the status quo: all of our CI builds will fail once we upgrade to 0.15.1, unless I explicitly add a build step to blow away `elm-stuff` first.

**Comment by evancz** [comment]
I can't imagine that the build artifacts are *too* massive, so versioned artifacts seems like a plausible solution for the foreseeable future. I imagine we'll get an issue in the future when someone with a big project is like "why do I keep all this extra old stuff?" but that seems like it's not the end of the world and should not block the "try two out at once" scenario when releases can be used together.

**Comment by evancz** [comment]
I think this is actually not too crazy a change. Anyone able to take a look?

**Comment by mgold** [comment]
FWIW, versioning by build system is a more functional (immutable) way to handle things. Wouldn't you hate for something to go wrong (network, corrupt file), and the build system for a _functional language_ deleted all the files that you now can't get back?

**Comment by evancz** [comment]
Close in favor of https://github.com/elm-lang/elm-plans/issues/1 ?

**Comment by rtfeldman** [comment]
Yep!

**Comment by evancz** [comment]
For the record, this is implemented now.

**Comment by rtfeldman** [comment]
![happydance](https://cloud.githubusercontent.com/assets/1094080/9793933/0f09c618-579d-11e5-979f-23b200796984.jpg)
