### ISSUE TITLE
Warnings from dependency packages on first time compile.

### ISSUE THREAD

**Issue by ajhager** [elm-lang/elm-make#31]
When you compile with either `--warn` or `--report=json`, just after you've run `elm-package install`, you get all the warnings from all the packages under elm-stuff the first run as they are being compiled. Most of these warnings are for "Native.SomeModule is unused". And since none of those files will get compiled again, the user never sees the warnings a second time. This can be very confusing the first time you compile in elm-vim with warnings enabled, for instance. Should unused native module warnings be suppressed? 

This also relates to #27 in that warnings are important, but you'll miss them for any modules that don't need to be recompiled. So perhaps warnings should always be an opt in that forces everything to be recompiled so all your files are linted.

**Comment by dnalot** [comment]
@rtfeldman This is the source of one issue you reported during Sublime beta testing.
