### ISSUE TITLE
No kind checking?

### ISSUE THREAD

**Issue by LiamGoodacre** [elm-lang/elm-make#35]
The following compiles:

~~~elm
type alias Oops = List List
oops : List List
oops = []
~~~

The following gives a funny error:

~~~elm
oops : List List
oops = [[]]
~~~

Error:

~~~
The type annotation for `oops` does not match its definition.
3| oops : List List

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    List

    List a
~~~

**Comment by jvoigtlaender** [comment]
This is certainly not the correct place to file this issue. Better at elm-compiler.

**Comment by evancz** [comment]
Yes, please move this over to elm-compiler. Also check to see if there is an issue open about this. I think there is?
