### ISSUE TITLE
Add a `--style="path/to/style.css"` option for when compiling to `.html`?

### ISSUE THREAD

**Issue by mitchmindtree** [elm-lang/elm-make#37]
Which would just add <link rel="stylesheet" href="path/to/style.css"> into the generated html head?

Something along these lines might be useful as there currently doesn't seem to be a way to programmatically link a stylesheet (please correct me if I'm wrong!).

**Comment by evancz** [comment]
I agree this could be useful. I do not want to track feature requests on this repo though. This is a known possibility.
