### ISSUE TITLE
--report=json doesn't return JSON

### ISSUE THREAD

**Issue by dnalot** [elm-lang/elm-make#38]
So far I've encountered 4 scenarios:

0. Compile fails. JSON returned.
0. Compile succeeds. JSON appended with string like `Successfully generated build/index.html`.
0. Regardless above I occasionally get JSON prepended like `Packages configured successfully!`
0. #26 

For now I'm splitting output on new lines and parsing them separately. But it's been error prone. Maybe make needs a JSON wrapper with keys like `result` and `status`.

**Comment by evancz** [comment]
Closing in favor of #46 which will fix this and others.
