### ISSUE TITLE
Cache invalidation bug when building multiple files

### ISSUE THREAD

**Issue by jwmerrill** [elm-lang/elm-make#4]
Running `elm-make` on two files in the same project fails to properly build the second file. E.g. if you run

```bash
elm-make --yes --output=build/a.html src/a.elm
elm-make --yes --output=build/b.html src/b.elm
```

then `build/b.html` ends up being identical to `build/a.html`.

I've created a repo at https://github.com/jwmerrill/elm-compiler-stale-cache to demonstrate this problem.

**Comment by evancz** [comment]
I think https://github.com/elm-lang/elm-make/commit/2e3f17798e480df59a668cefb87746dea11ed1e7 and https://github.com/elm-lang/elm-make/commit/d6f4f569d4c48995f2b874c81a1738118430c1c5 should resolve the issues we are seeing here.

If you can build from source, please do and let me know. If you cannot, I'll have installers relatively soon.

**Comment by evancz** [comment]
Alright, the fix should appear in [the alpha Mac and Windows installers](https://groups.google.com/forum/#!topic/elm-discuss/KHg-aeFvDN0). Please give it a try and let me know (1) which installer you use and (2) if the issue is resolved.

**Comment by jwmerrill** [comment]
The example repo now works as expected for me on 0.14.1. I built it from source by checking out the latest `elm-platform` and running `runhaskell src/BuildFromSource.hs 0.14.1`.

I'll close this issue, since it looks like it is now resolved. Thanks!
