### ISSUE TITLE
Error when generating the html output: commitAndReleaseBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by grzegorzbalcerek** [elm-lang/elm-make#40]
I am trying to compile a simple program and I am getting an error when generating the html output.
Here is a simple session, where I start with a folder that contains only the source file.

    C:\Users\grzes\tmp>dir
     Volume in drive C is Windows8_OS
     Volume Serial Number is 22AA-55EE

     Directory of C:\Users\grzes\tmp

    2015-08-14  02:34    <DIR>          .
    2015-08-14  02:34    <DIR>          ..
    2015-08-14  02:32                76 Hello.elm
                   1 File(s)             76 bytes
                   2 Dir(s)   9 035 051 008 bytes free

    C:\Users\grzes\tmp>more Hello.elm
    module Hello where
    import Markdown
    main = Markdown.toElement """Hello"""

    C:\Users\grzes\tmp>elm package install evancz/elm-markdown --yes
    Downloading elm-lang/core
    Downloading evancz/elm-html
    Downloading evancz/elm-markdown
    Downloading evancz/virtual-dom
    Packages configured successfully!

    C:\Users\grzes\tmp>elm make Hello.elm --output Hello.html
    Success! Compiled 38 modules.
    elm-make.exe: Hello.html: commitAndReleaseBuffer: invalid argument (invalid character)

    C:\Users\grzes\tmp>

I am using elm 0.15.1 on Windows.

    C:\Users\grzes\tmp>elm
    Elm Platform 0.15.1 - a way to run all Elm tools
    ...

I have installed from source.

The HTML is generated but the browser shows a blank page with no content.

    C:\Users\grzes\tmp>dir
     Volume in drive C is Windows8_OS
     Volume Serial Number is 22AA-55EE

     Directory of C:\Users\grzes\tmp

    2015-08-14  02:35    <DIR>          .
    2015-08-14  02:35    <DIR>          ..
    2015-08-14  02:34               426 elm-package.json
    2015-08-14  02:35    <DIR>          elm-stuff
    2015-08-14  02:32                76 Hello.elm
    2015-08-14  02:35           193 455 Hello.html
                   3 File(s)        193 957 bytes
                   3 Dir(s)   9 030 238 208 bytes free

    C:\Users\grzes\tmp>

The error is not shown when generating JS.

    C:\Users\grzes\tmp>elm make Hello.elm --output Hello.js
    Success! Compiled 0 modules.
    Successfully generated Hello.js

**Comment by grzegorzbalcerek** [comment]
Not sure if that might be important. But my Windows system is in Polish. Could that introduce an invalid character somewhere?

**Comment by jvoigtlaender** [comment]
If it *is* a character encoding problem caused by your language setting, maybe [this](https://github.com/elm-lang/elm-make/issues/33) is relevant or could even help your situation.

**Comment by dnalot** [comment]
I get this trying to compile on Windows with Unicode characters c.f. [Hakyll](http://jaspervdj.be/hakyll/tutorials/faq.html).

**Comment by artgitt** [comment]
This might be relevant
https://www.reddit.com/r/haskell/comments/37y0cz/little_bug_hunting_help_stdout/

**Comment by stormont** [comment]
I also get this error doing a straight copy/paste of the HTTP Tasks part of the Reactivity tutorial: http://elm-lang.org/guide/reactivity

Using elm-make to compile to elm.js works fine; it only exhibits the error when compiling to HTML.

Specifically, the HTML generation stops shortly after the third real usage of the "smartypants" field. Comparing to the full elm.js, it looks like it's halting on these characters:

* return text.replace(/--/g,"â€”")

The HTML output simply ends with this:

* return text.replace(/--/g,"

(I'm in the US, if that helps with tracking down the necessary encodings.)

**Comment by deadfoxygrandpa** [comment]
I'm now seeing this error on Windows 7 using Elm 0.16.0.

**Comment by adicirstei** [comment]
Any news on this?

**Comment by ianrae** [comment]
Seeing this error on Windows 8 and Elm 0.16.  Am working through http://elm-by-example.org/chapter1helloworld.html.    HelloWorld1, 2, and 3 work fine.  HelloWorld4 (which requires elm-markdown) has the error.

**Comment by nmdanny** [comment]
Encountered this error on the [reactivity guide](http://elm-lang.org/guide/reactivity) at the HTTP Tasks part.

**Comment by philderbeast** [comment]
As reported by others in this thread and from the Hakyll link, on windows running `chcp 65001` fixed this problem for me.

**Comment by evancz** [comment]
I believe @jvoigtlaender resolved this.
