### ISSUE TITLE
Coherent format for --report=json

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-make#47]
Right now the JSON spit out is haphazard. Folks don't like that warnings and errors are separate. It'd be good to add information about successes, dependency structure, etc.

Issues that touch on this include: #42, #25

**Comment by rhencke** [comment]
Having just gone through implementing something parsing the JSON output - I'd like to add one more thing to the wish list - omitting the 'Successfully generated <target>' message when writing JSON output.  (The exit code can be used to check this if need be, instead)
