### ISSUE TITLE
Unable to upgrade packages behind proxy

### ISSUE THREAD

**Issue by Deimos28** [elm-lang/elm-make#48]
On versions 0.15, 0.15.1 and 1eaec5b (of elm-package), elm-make fails with the following output:

Elm-Platform/master/bin $ ./elm make
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
failed with 'ProxyConnectException "github.com" 443 (Left "StatusHeaders (Status {statusCode = 400, statusMessage = \"Bad Request\"}) HTTP/1.1 [(\"Date\",\"Wed, 26 Aug 2015 07:12:07 GMT\"),(\"Server\",\"Apache/2.2.3 (Red Hat)\"),(\"Content-Length\",\"303\"),(\"Connection\",\"close\"),(\"Content-Type\",\"text/html; charset=iso-8859-1\")]")' when sending request to
    <http://github.com/elm-lang/core/zipball/2.1.0/>

The following environment variables are set:

$ echo $http_proxy
http://130.11.124.6:80
$ echo $https_proxy
http://130.11.124.6:80

I thought this was related to [Issue 132 of http-client](https://github.com/snoyberg/http-client/issues/132) but it was fixed in version 0.4.16 and elm master is using version 0.4.20.

**Comment by evancz** [comment]
Thanks for the thorough report and suggested fix! This was observed in https://github.com/elm-lang/elm-package/issues/113 and led to the version bump to get the later version of http-client.

Unfortunately, I can't repackage all the installers right now, but this fix will definitely be out with the next release of Elm.
