### ISSUE TITLE
Add CommonJS/Node/AMD snippet to end of compiled output

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-make#50]
See https://github.com/elm-lang/elm-compiler/issues/1029 for discussion that led to this.

The following should be incorporated into the output JS of compiled Elm files.

```javascript
(function() {
  var Elm = ... // current emitted code goes here

  if (typeof define === "function" && define.amd) {
    define([], function() {
      return Elm;
    });
  } else if (typeof module === "object") {
    module.exports = Elm;
  } else {
    if (typeof this.Elm === "undefined") {
      this.Elm = Elm;
    } else {
      throw new Error("This page is trying to import multiple compiled Elm programs using the same `Elm` global object, which would cause conflicts. This can be resolved by using a module loader like RequireJS to import the compiled Elm programs into different objects.")
    }
  }
}).call(this);
```

**PREVIOUS VERSION:**

This version is more "stock" and will silently overwrite any previous `Elm` globals defined on the page...which seems far less desirable than crashing early with a helpful message.
```javascript
(function() {
  var Elm = ... // current emitted code goes here

  if (typeof define === "function" && define.amd) {
    define([], function() {
      return Elm;
    });
  } else if (typeof module === "object") {
    module.exports = Elm;
  } else {
    this.Elm = Elm;
  }
}).call(this);
```

**Comment by rtfeldman** [comment]
Just updated the original description to handle a case we ran into: if you add multiple compiled Elm programs to the same page, bad things will happen, so this will now:

1. Prevent that from happening
2. Explain to the user why that would be bad
3. Recommend an alternative

**Comment by itrelease** [comment]
https://github.com/elm-lang/elm-make/pull/63

**Comment by rtfeldman** [comment]
Awesome! :tada:

**Comment by evancz** [comment]
Here is a version that uses an "early return" style that I think is easier to read.

```javascript
	if (typeof define === "function" && define.amd)
	{
		define([], function() { return Elm; });
		return;
	}

	if (typeof module === "object")
	{
		module.exports = Elm;
		return;
	}
	
	if (typeof this.Elm === "undefined")
	{
		this.Elm = Elm;
		return;
	}

	throw new Error("blah blah blah");

}).call(this);
```

No need to do a PR or anything. I'll do it in the appropriate way.
