### ISSUE TITLE
Invalid cabal dependency

### ISSUE THREAD

**Issue by maxgurewitz** [elm-lang/elm-make#55]
Hello,

I was trying to build your project and I ran into a problem.  I believe your cabal dependencies are invalid. Specifically, 

    elm-compiler >= 0.15.1 && < 0.16,

given that the available versions on hackage are,

    0.14, 0.14.1, 0.15

http://hackage.haskell.org/package/elm-compiler.

Thanks,

Max

**Comment by jvoigtlaender** [comment]
The Hackage page you link to says that stuff is deprecated. Indeed, current versions of Elm are not any longer found on Hackage. If you want to build from source, look here: https://github.com/elm-lang/elm-platform (except that while there it says you should set your `PATH` variable after running the install script, you actually have to do it before that).
