### ISSUE TITLE
elm-make or compiler gets state corrupted, needs manual reset

### ISSUE THREAD

**Issue by Dedoig** [elm-lang/elm-make#57]
Here is what happened:

- worked on a small project (3 modules) for a few hours
- introduced an type-error across 2 modules and noticed it was not caught by elm-make
- manually deleted the elm-stuff directory and re-ran elm package install
- ran elm-make again and it caught the type error

So it seems some state got corrupted in elm-stuff. I cannot provide a repeatable test. 

Versions: elm-make 0.2 (Elm Platform 0.15.1)

**Comment by Dedoig** [comment]
Hmm. I wonder if this is related to git. Does `elm-make` use file timestamps to minimize rebuilds? 

My `elm-stuff` is `gitignored`. If I switch git branches could I end up with older time-stamped sources, and newer (but inapplicable) previous build artifacts, leading `elm-make` to think rebuilds are not needed?

**Comment by evancz** [comment]
It does indeed use "modification time" to decide if something needs recompilation. I'm not sure there's a way around that really though.

**Comment by Dedoig** [comment]
Hmm. It just happened again, this time with no git-related activity at all. In fact I stopped doing any git stuff after that last error, just in case, even though my `elm-stuff` directory is `.gitignored`.

So right now the program compiled, then I made some types opaque in a module, which should have triggered compile errors in the using module. `elm-make` gave no errors.

Then I did `rm -rf elm-stuff/*` and this time `elm-make` gave the compile errors I expected (after it reinstalled required packages).

I cannot think of a way to reproduce this, but I don't believe it is operator error. Anyone seen similar issues elsewhere?

**Comment by evancz** [comment]
What OS are you on? How did you install?

What are the names of all of your modules? Do you have modules with the same name in a single project? Are you shadowing module names from dependencies?

**Comment by Dedoig** [comment]
- OSX 10.9.4 
- Installed using the elm-lang.org Mac installer
- Module names: Input, Wrapper, Cpu, Main
  - Dependencies: elm-lang/core, evancz/elm-effects, evancz/elm-html
  - No Native stuff
- No duplicate or shadowed module names

Let me know if I there is something diagnostic I should try.

**Comment by evancz** [comment]
I suspect this is explained by #72 if you are compiling individual modules rather than always compiling from the root. The temporary fix is to just compile from the root of your project (whatever module has `main` in it). The compiler is very fast, so it shouldn't be a big deal.

I'm going to assume my theory is correct and close this one in favor of the more specific one.
