### ISSUE TITLE
feature request: elm make clean

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-make#60]
Occasionally, I've managed to get elm into a bad state. Not entirely sure how to reproduce but it goes something like this:

1. Install something with `elm package`
1. Use that thing for a while
1. Remove that dependency 
1. Cached built JS gets out of step
1. Die at runtime

When this happens, its no big deal, and can be fixed by going into the `elm-stuff` folder and deleting my own user folder. When running make next time, as is well! However I don't like touching `elm-stuff`, so I'd like to request a way to clean out cached JS files. Perhaps a command like:

```
elm make clean
```

**Comment by joeandaverde** [comment]
+1

**Comment by evancz** [comment]
Tracking from meta issue #98

**Comment by theor** [comment]
Woudl rm elm-stuff be acceptable, at least in a first time ?
