### ISSUE TITLE
Print errors to stderr instead of stdout

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-make#70]
In elm-test we generate a temporary .js file for the compiled `Test.elm` before running the tests.

By default that means we get output like this every time the tests run:
```
Successfully generated /var/folders/f2/bgdp00xs327b2qx7mmg6jkbh0000gn/T/elm_test_1151022-3235-1bxa84u.js
Successfully compiled Test.elm
```

This is pretty ugly, so what we've been doing is piping `elm-make`'s stdout and discarding lines that start with "Success". This works, but introduces a new problem: because we're piping the output instead of just giving `elm-make` direct access to the console, we miss out on colorized error messages. (Thanks @evancz for pointing out the culprit!)

If `elm-make` wrote error messages to `stderr` and success messages to `stdout`, we could continue to pipe the `stdout` stream for filtering, but let `stderr` pass through as normal (colors and all), meaning everything would be rad and awesome!

**Comment by itrelease** [comment]
@rtfeldman can you provide example for your case so I can reproduce your problem?

**Comment by rtfeldman** [comment]
Sure, just take a look at https://travis-ci.org/rtfeldman/node-elm-test - it currently works as described above. :smiley:

**Comment by itrelease** [comment]
@rtfeldman that was fast :+1: thanks

**Comment by jvoigtlaender** [comment]
On the other hand, https://github.com/elm-lang/elm-make/pull/32 argues that the success messages should go to `stderr` as well.

**Comment by rtfeldman** [comment]
True, but it argues that based on an explicitly unsupported motivating use case. I commented over there.

**Comment by evancz** [comment]
Tracked in #98
