### ISSUE TITLE
case statement that causes elm-make 0.16 to hang or crash

### ISSUE THREAD

**Issue by fredcy** [elm-lang/elm-make#74]
The following code causes elm-make 0.16 to hang on my OS X 10.10.5 machine, using all the CPU. It also causes my clone of elm-lang.org to crash the snap server when I try to compile the code in the equivalent of the elm-lang.or/try page. I found the code in this posting: https://elmlang.slack.com/archives/general/p1450513501003246

@evancz This might be the kind of code that can bring down the snap server on elm-lang.org.

``` elm
step2a' : List Char -> List Char
step2a' drow =
  case drow of
    'l' :: 'a' :: 'n' :: 'o' :: 'i' :: 't' :: 'a' :: mets ->
      []
    'l' :: 'a' :: 'n' :: 'o' :: 'i' :: 't' :: mets ->
      []
    'i' :: 'c' :: 'n' :: 'e' :: mets ->
      []
    'i' :: 'c' :: 'n' :: 'a' :: mets ->
      []
    'r' :: 'e' :: 'z' :: 'i' :: mets ->
      []
    'i' :: 'l' :: 'b' :: mets ->
      []
    'i' :: 'l' :: 'l' :: 'a' :: mets ->
      []
    'i' :: 'l' :: 't' :: 'n' :: 'e' :: mets ->
      []
    'i' :: 'l' :: 'e' :: mets ->
      []
    'i' :: 'l' :: 's' :: 'u' :: 'o' :: mets ->
      []
    -- 'n' :: 'o' :: 'i' :: 't' :: 'a' :: 'z' :: 'i' :: mets ->
    --   ifMeasure 0 drow mets ['e', 'z', 'i']
    'a' :: 'b' :: mets ->
      []
    'a' :: 'b' :: mets ->
      []
    'a' :: 'b' :: mets ->
      []
    'a' :: 'b' :: mets ->
      []
    'a' :: 'b' :: mets ->
      []
    _ ->
      drow
```

**Comment by evancz** [comment]
This is because of the pattern match compiler that came with 0.16. It is trying to be more sophisticated such that it does not run checks multiple times. It seems to have pretty bad worst case performance though, so I believe this will terminate eventually. So this is an elm-compiler thing.
