### ISSUE TITLE
feature request: add output-dir option

### ISSUE THREAD

**Issue by abnud1** [elm-lang/elm-make#77]
I think an output-dir option would be great, for example if I have an src dir where I put my Modules, I would like to do something like this :  
`elm make src/* --output-dir html`
then all compiled files would be in html directory .  

If I want the output to be in js then maybe a format option is needed.  

I think this is particularly good if you want to have your js output ready to be put in a web server public directory for serving.

**Comment by evancz** [comment]
Tracking from meta issue #98
