### ISSUE TITLE
Implementing short description for elm-make when no arguments provided.

### ISSUE THREAD

**Issue by suvash** [elm-lang/elm-make#8]
I had my first experience with elm-make today. After a bit of asking around and peeking into documentation, I did manage to use to build an Elm file.

I also did try `-h` to find the usage of `elm-make`. However, I sorta guessed that it would be a valid option. It would be great if a short usage info could be provided when no arguments were supplied. This would really help with a first time experience.

Something like
```
elm-make 0.1, (c) Evan Czaplicki 2014

-h, --help for help
```

**Comment by evancz** [comment]
Closing in favor of #23 which outlines a comprehensive way to improve this. Thanks for reporting this, I agree it is quite confusing as is! I was not thinking about the beginner experience when I made it that way.
