### ISSUE TITLE
elm-package.json does not allow BitBucket repositories

### ISSUE THREAD

**Issue by proehlen** [elm-lang/elm-make#80]
```
Error reading file elm-package.json:
    Problem with the `repository` field.

The given domain does not start with <https://github.com/>
```
Is there something about Elm that requires Github?  I use Github and Bitbucket interchangeably for different reasons and as far as I can tell they are nearly 100% compatible.

**Comment by proehlen** [comment]
Also, if I can't nominate a Bitbucket repo, I'd rather just leave this out but it's a required field:

```
Error reading file elm-package.json:
    Missing field "repository", a link to the project's GitHub repo.
    Check out an example elm-package.json file here:
    <https://raw.githubusercontent.com/evancz/elm-html/master/elm-package.json>
```

**Comment by jvoigtlaender** [comment]
@proehlen, please close this issue. It's a duplicate. See #59 and #71.

**Comment by proehlen** [comment]
Apologies @jvoigtlaender - I didn't see 71.
