### ISSUE TITLE
Feature request: Option to nominate path of elm-stuff or configure it to be a hidden directory

### ISSUE THREAD

**Issue by proehlen** [elm-lang/elm-make#81]
I can explain the use-case if you want me to but basically at the moment I'm forced to delete elm-stuff after every build which obviously slows down every subsequent re-build.

**Comment by proehlen** [comment]
Actually, I found I can get around the issue by hiding/un-hiding the directory in my build script.  Feel free to close this issue if you think the feature isn't valuable.
```
#!/bin/bash
cd /Users/Peter/Git/clrflow/client/
mv .elm-stuff elm-stuff # reuse last build
elm make Main.elm --output=compatibility/clrflow.js --warn
mv elm-stuff .elm-stuff # hide build stuff so Meteor doesn't load the javascript files
```

**Comment by evancz** [comment]
Tracking from meta issue #98

**Comment by evancz** [comment]
I'm removing from the meta issue. I think we have generally decided that predictability is worth the trade offs.

- Having hidden directories can be really confusing. I personally hate having them secretly placed all over my computer.
- Having all Elm projects look basically the same is very valuable. If I can drop into a project and know exactly where everything will be, that can save me hours of wondering about stuff.

So on net, I think the value to specific expert users wanting to customize things is not worth the costs to other Elm users.
