### ISSUE TITLE
Add --only-dependencies

### ISSUE THREAD

**Issue by wolverian** [elm-lang/elm-make#84]
Reason: I want to avoid the slow rebuilding of dependencies on each build on a CI service.

Motivation: I use CircleCI.com as a CI service. Each build is started with a clean disk by default.

They support caching dependencies. I can use `elm package install` to install dependencies and cache them, but that doesn't actually build the dependencies, so it caches just the sources. 

I want to cache the built dependencies too.

**Comment by wolverian** [comment]
Additional note: you can of course just build the project and then cache the dependencies, but that might lead to caching too much (i.e. I don't want to dirty the cache with builds of my own sources).

**Comment by jvoigtlaender** [comment]
@wolverian, doesn't `elm-make` without parameters do exactly what you want?

**Comment by evancz** [comment]
Tracking from meta issue #98
