### ISSUE TITLE
Add flag to print resolved dependency tree

### ISSUE THREAD

**Issue by joeandaverde** [elm-lang/elm-make#87]
It would be helpful to be able to see the result of: 

https://github.com/elm-lang/elm-make/blob/b73a26c52a7dbc17cab0fec26ea11fe0d3624b68/src/Pipeline/Crawl.hs#L36

The specific use case is for working with file watchers to know when to invoke a new compilation.

**Comment by evancz** [comment]
Tracking from meta issue #98
