### ISSUE TITLE
Feature request: --force-rebuild

### ISSUE THREAD

**Issue by emanuelkoczwara** [elm-lang/elm-make#88]
Hello,

It would be nice if I could do:

```
$ elm-make Main.elm --force-rebuild --warn
```

For now I can just remove elm-stuff/build-artifacts/, but it would be great if elm-make could do that for me. Maybe `--force-full-rebuild` will be also good, that should remove whole elm-stuff/ before compilation. Is it desirable to have such features in elm-make or we should use some build system for that?

**Comment by evancz** [comment]
Tracking from meta issue #98

**Comment by Natim** [comment]
> For now I can just remove elm-stuff/build-artifacts/,

In my case removing only `elm-stuff/build-artifacts/*/user/project` was sufficient.

**Comment by Natim** [comment]
@evancz Any idea why elm-make doesn't detect the changes to the .elm file?

I am basically doing a `sed -i` command to one of the file of my project in order to build it for various HTTP APi endpoints and it doesn't recompile it after each changes.
