### ISSUE TITLE
minification flag?

### ISSUE THREAD

**Issue by geekyme** [elm-lang/elm-make#91]
Either `elm-make` doesn't have this or I'm not looking hard enough.

**Comment by evancz** [comment]
I do not think `elm-make` should be in charge of this. There are tons of great JS minifiers out there, and if you have a proper production system, you are probably already using one of them. I don't want to mandate what people end up using, so I just produce JS.

That said, the next release of Elm will have JS output that gets a lot more milage from things like Google Closure Compiler.
